### PR TITLE
Replaced `npx cap update android` with ionic quivalent

### PR DESCRIPTION
**Pull request by RohanTalip**
##  What does this PR accomplish?
Replaced `npx cap update android` with `ionic capacitor update android` for consistency with the other commands.

## Did you add any dependencies?
n/a

## How did you test the change?
I ran the command.

### CODE REVIEW

**Comment by epicfaace** [comment]
@RohanTalip can you push an empty commit so the netlify build will be fixed?

**Comment by RohanTalip** [comment]
> @RohanTalip can you push an empty commit so the netlify build will be fixed?

Done.  What was/is the issue though?

**Comment by RohanTalip** [comment]
Could someone please merge this?  I don't have the necessary permissions to do so.

**Comment by SamMousa** [comment]
We've blocked all ionic stuff for now @RohanTalip, more info during standup / eng

**Comment by RohanTalip** [comment]
Thanks @SamMousa .  I just caught up with the updates in #eng and I'm getting caught up with #release

**Comment by advayDev1** [comment]
Thanks for the PR!  Per our discussion this morning, we are committed to Flutter for the client, so closing these out for now.

**Pull request closed without merging**
