### PR TITLE
Some more process guidelines

### PR DESCRIPTION
**Pull request by advayDev1**

### CODE REVIEW

**Comment by SamMousa** [comment]
Why squash commits before a PR? We can do it when merging right?

I'm not a fan of squashing tbh, it loses information and the clean view can also be created by tooling.

Not a big deal if we do decide to squash though.

**Comment by advayDev1** [comment]
IMO: a dev's internal back and forth and debugging process can cause confusion for later readers.  Having the committer squash them I believe destroys some of the author's commit metadata.

But I'm fine with either.

**Comment by advayDev1** [comment]
@hspinks you have a preference?  Author to squash, or committer to squash?

**Comment by advayDev1** [comment]
(One downside of not squashing at all is that all the unreviewed interim code is still checked in - would have to consider security/licensing of those intermediate commits being in the repo)

**Comment by hspinks** [comment]
personal preference is not to squash, or if we do, squash when merging. ideally even in dev process, we are not committing during a back-and-forth debugging, only when we get to a meaningful point that can be committed. I'm open to other thoughts on this though

**Pull request closed without merging**
