### PR TITLE
Use WebP format for the logo image and precache it to improve performance

### PR DESCRIPTION
**Pull request by PieterAelse**
- [x] Provided detailed pull request description and a succinct title (consider template below for guidance).
- [x] Tested your changes, especially after any code review iterations.
- [ ] Included any relevant screenshots of UI updates. 
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Verified all contributions are properly licensed pursuant to the [LICENSE](https://github.com/WorldHealthOrganization/app/blob/master/LICENSE) file in the root of the repository.
- [x] Verified your name is in the [content/credits.yaml](https://github.com/WorldHealthOrganization/app/blob/master/content/credits.yaml) file (if you want it to be).

## What does this PR accomplish?

Use WebP for the logo and precache it.

Details:
- Using WebP instead of JPG for the logo decreased the size from 330.64KiB to 206.51KiB (-37.54%).
- Using `preCacheImage` improves the performance of loading this (big!) logo

Improves https://github.com/WorldHealthOrganization/app/issues/482 

What more could be done to improve the situation:
- [ ] Use 1x/2x/3x versions of the logo (can the designers supply this?)
- [ ] Use an image with a transparent background. Now the background is white, while the background of the app is off-white, a bit more grey. So the exact border of the logo can also be seen.

## Did you add any dependencies?

No

## How did you test the change?

Visually, as I don't have the web-knowledge to read the performance tools in Chrome.
For what I can see it improves it, but it's not a complete fix yet.

### CODE REVIEW

**Comment by advayDev1** [comment]
Your commit does not use your github email address @PieterAelse - Please correct.

**Comment by PieterAelse** [comment]
@advayDev1 Looks ok now? Otherwise I need to dive into my config settings 😛

**Comment by advayDev1** [comment]
@PieterAelse I still see both, can you do `git commit --amend --reset-author`

**Comment by PieterAelse** [comment]
@advayDev1 Fixed now (also merge conflicts)! Thanks, did not know that one yet.

**Comment by advayDev1** [comment]
Per discussion holding off on this for v1.

**Comment by PieterAelse** [comment]
Closing PR as issue is also closed.

**Pull request closed without merging**
