### PR TITLE
Propagate relicense of madvay/actions-sandbox

### PR DESCRIPTION
**Pull request by advayDev1**
For ease of the upcoming attempted relicense I've relicensed my underlying repository linked here to Apache 2.

The only people who seem to have worked on the files I pulled over into this repo seem to be @brunobowden and @hspinks .  If you both agree to this relicense by saying "I agree" I will remove the VOID and Bruno can submit.
As always this is not legal advice and I cannot represent that this is legally sufficient to perform the relicense.

Please note that if you don't submit this now, it is possible others (other than Hunter and Bruno) will further adapt my sandbox-licensed work and you may need more agreements here.

### CODE REVIEW

**Comment by brunobowden** [comment]
I agree. Thank you Advay

**Comment by brunobowden** [comment]
@advayDev1 - was this just used as an experimental sandbox? My impression was that there wasn't any dependencies on `actions-sandbox`. If there were, then I'd be inclined to bring the code in to WHO/app repo with your permission but I don't think we need to.

**Review by brunobowden — APPROVED** [review]

**Comment by advayDev1** [comment]
I directly copied workflows and scripts into this codebase, hence the copyright notice.  There is no dependency intentionally.

**Comment by hspinks** [comment]
I agree

**Comment by advayDev1** [comment]
thanks hunter over to @brunobowden

**Comment by brunobowden** [comment]
Thanks @advayDev1

**Pull request merged**
