### PR TITLE
fix: add semantics to settings page analytics switch

### PR DESCRIPTION
**Pull request by britannio**
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the PR).**
- [x] REQUIRED: Do you have an Issue **assigned to you** within the v1 milestone for this PR?  Put the Issue number here: https://github.com/WorldHealthOrganization/app/issues/926
- [x] Provided detailed pull request description and a succinct title (consider template below for guidance).
- [x] Tested your changes, especially after any code review iterations.
- [x] Included any relevant screenshots of UI updates.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Verified all contributions are properly licensed pursuant to the [LICENSE](https://github.com/WorldHealthOrganization/app/blob/master/LICENSE) file in the root of the repository.
- [x] Verified your name is in the [content/credits.yaml](https://github.com/WorldHealthOrganization/app/blob/master/content/credits.yaml) file (if you want it to be).

After all boxes above are checked, request and receive an Approved review from any team member knowledgable in the area (TODO team member list).  Once approved, the team member will assign your review to a Committer or use the `needs-merge` label.

## What does this PR accomplish?
- Closes https://github.com/WorldHealthOrganization/app/issues/926
- TalkBack now reads "**Ticked/Not Ticked** Analytics, Allow WHO to collect analytics for product improvement using Google Analytics **switch, double-tap to toggle**"
- Wrap the whole section in an InkWell

## Did you add any dependencies?
No

## How did you test the change?
Using TalkBack on my Android device

Screenshot_20200407-170907

### CODE REVIEW

**Comment by britannio** [comment]
Blocked until I verify that the new screen reader message is correct.

**Comment by britannio** [comment]
> Blocked until I verify that the new screen reader message is correct.

It's reading the same message as the `SwitchListTile()` message.

**Comment by avkvirtru** [comment]
@britannio this doesn't seem to work in VoiceOver. The label appears, but there are no traits to identify the toggle as interactive when it's off or that it's in the off / not selected state.

**Comment by britannio** [comment]
> @britannio this doesn't seem to work in VoiceOver. The label appears, but there are no traits to identify the toggle as interactive when it's off or that it's in the off / not selected state.

Interesting, I've reopened the issue.

**Pull request merged**
