### PR TITLE
Ran "npx sort-package-json"

### PR DESCRIPTION
**Pull request by RohanTalip**
## What does this PR accomplish?

Ran "npx sort-package-json" to get a deterministic order of keys/entries.

See https://github.com/keithamus/sort-package-json

## Did you add any dependencies?

No.

## How did you test the change?

n/a

### CODE REVIEW

**Comment by epicfaace** [comment]
Why is this helpful?

**Comment by SamMousa** [comment]
I'm not in favor of running this just once.
If we want this, in my opinion, we should add it to CI as well, ie refuse a PR if the new format isn't the same as what we currently have.

This however would mean adding a few devdependencies. Before you create a pr for that be sure to check if the dependencies are okay.

**Comment by RohanTalip** [comment]
> I'm not in favor of running this just once.
> If we want this, in my opinion, we should add it to CI as well, ie refuse a PR if the new format isn't the same as what we currently have.

Sure, I was thinking of doing that too, but wanted to see if this would even fly with people here before investing time into the CI side of things.

> This however would mean adding a few devdependencies. Before you create a pr for that be sure to check if the dependencies are okay.

What's your criteria for the dependencies being OK?

**Comment by SamMousa** [comment]
Dependencies are more @advayDev1 's cup of tea.
For this case, (ie it is non-essential), i'd be okay if it is all MIT licensed, which it is.
Furthermore, what it does is simple and we could at any time remove it or re-implement it.

Note though that since we might move frameworks you might not want to invest in CI.

**Comment by myiremark** [comment]
Also want to be careful of malicious code being inserted into dependencies.  WHO is a high value target and already has been targeted recently.

**Comment by epicfaace** [comment]
I don't think there's enough value in adding a package.json-sorting-step to CI that would justify the effort required to set it up or maintain it.

**Pull request closed without merging**
