### PR TITLE
Publish artifacts on CI build

### PR DESCRIPTION
**Pull request by epicfaace**
## What does this PR accomplish?

Publish iOS and Android app files on the CI build task so that they can be downloaded once the build has been finished. This will help us to use Firebase App Distribution, because we can download these builds and then upload them to Firebase (at least until we get fastlane setup) -- this is better than a developer building the app on their own computer and then uploading that app.

Also run build on any push to master, release/* branches, so that artifacts are built for these branches. This will not slow down speed of PRs because the build will only be run after the PR has been merged.

## Did you add any dependencies?

publish artifacts - official github actions

### CODE REVIEW

**Comment by SamMousa** [comment]
The builds here won't have private assets though?

**Comment by SamMousa** [comment]
What about a nightly build triggered from the build tools repo? There we can also put the necessary secret keys in

**Comment by SamMousa** [comment]
I'm actually good with merging this @epicfaace. Even if it does not contain all the assets, it can be handy to get those artifacts.

**Comment by SamMousa** [comment]
@epicfaace please resolve conflicts and we can merge this!

**Comment by advayDev1** [comment]
> This will not slow down speed of PRs because the build will only be run after the PR has been merged.

But it runs on PRs too.  See your own PR's artifacts :)

**Comment by epicfaace** [comment]
@advayDev1 

> But it runs on PRs too. See your own PR's artifacts :)

That's because this PR modifies a file in `.github/workflows` -- `flutter build` would have been run regardless of the workflow changes in this PR.

This PR only adds triggers to the `push` event -- which happen only after a PR is merged. See [this comment](https://github.community/t5/GitHub-Actions/Trigger-workflow-only-on-pull-request-MERGE/m-p/43313/highlight/true#M5329) for more details, as well.

**Comment by advayDev1** [comment]
@epicfaace that's not what i mean.  the uploading of artifacts happens on every commit to a PR, not just on the main branch.  is that your intention?  we upload 550mb for each commit?

**Comment by epicfaace** [comment]
Closing this, because we're already in the process for setting up a CI process for uploading to Firebase App Distribution (see #1293) -- so there is no need to publish builds as artifacts.

**Pull request closed without merging**
