### PR TITLE
🐛 Fix: CarouselView close/X button ripple effect draws over page content

### LINKED ISSUE #390: 🐛 CarouselView close/X button touch ripple effect overdrawn by page content of PageView
The touch ripple effect of the close button of the CarouselView widget is overdrawn by the content of the PageView in the same widget:

image

### PR DESCRIPTION
**Pull request by JulianAssmann**
- [✔️] Provided detailed pull request description and a succinct title (consider template below for guidance).
- [✔️] Tested your changes, especially after any code review iterations.
- [✔️] Included any relevant screenshots of UI updates.
- [✔️] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [✔️] Verified all contributions are properly licensed pursuant to the [LICENSE](https://github.com/WorldHealthOrganization/app/blob/master/LICENSE) file in the root of the repository.
- [✔️] Verified your name is in the [content/credits.yaml](https://github.com/WorldHealthOrganization/app/blob/master/content/credits.yaml) file (if you want it to be).

## What does this PR accomplish?
Fixes an visual error where the close button ripple effect on touch of the widget `CarouselView` was overdrawn by the page content shown. Fixes #390.

## Did you add any dependencies?
No.

## How did you test the change?
Running the app and testing the visual change manually. See screenshots:

Before: 
image
After: 
image

### CODE REVIEW

**Comment by advayDev1** [comment]
Thank you for your contribution.  However, please follow our PR checklist/template here:
https://raw.githubusercontent.com/WorldHealthOrganization/app/master/.github/pull_request_template.md - thanks!

**Comment by creativecreatorormaybenot** [comment]
I do not think this is how this should be fixed. I already did this in #359. Having said that, I will fix it again in another PR. If you think that your fix is superior, maybe elaborate in #432.

**Comment by JMcKiern** [comment]
@creativecreatorormaybenot 
In your PR, you set the color of the CarouselSlide Card to `Colors.transparent`. That might be a nicer solution. I don't really know enough to comment. However, your solution doesn't deal with the clipping caused by the title card. I suppose that would have to be set to transparent too? What are the merits of doing it this way?

To contrast, in this PR, a custom InkWell is being defined.

**Comment by creativecreatorormaybenot** [comment]
@JMcKiern See #440.

**Comment by patniemeyer** [comment]
Thank you all for your time and work on this - it is appreciated.  However the carousel has been removed from the new design so I'm going to close this for now.

**Pull request closed without merging**
