### PR TITLE
Update protect_yourself.en.yaml with simple HTML

### PR DESCRIPTION
**Pull request by purpledrosophila**
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the PR).**
- [ x] REQUIRED: Do you have an Issue **assigned to you** within the v1 milestone for this PR?  Put the Issue number here: 1030
- [ x] Provided detailed pull request description and a succinct title (consider template below for guidance).
- [ x] Tested your changes, especially after any code review iterations.
- [ x] Included any relevant screenshots of UI updates.
- [x ] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [ x] Verified all contributions are properly licensed pursuant to the [LICENSE](https://github.com/WorldHealthOrganization/app/blob/master/LICENSE) file in the root of the repository.
- [ x] Verified your name is in the [content/credits.yaml](https://github.com/WorldHealthOrganization/app/blob/master/content/credits.yaml) file (if you want it to be).

After all boxes above are checked, request and receive an Approved review from any team member knowledgable in the area (TODO team member list).  Once approved, the team member will assign your review to a Committer or use the `needs-merge` label.

## What does this PR accomplish?

Adds simple HTML to English "Protect Yourself" change

Made a slight change for readability, said "greater than 3 feet" rather than ">3 feet" because screen readers don't always handle the "greater than" HTML entity well. Also, highlighted key phrases in bold, rather than italics, because bold is easier to read for accessibility purposes.

1030

## Did you add any dependencies?

N/A

## How did you test the change?

N/A

### CODE REVIEW

**Comment by advayDev1** [comment]
Please add screenshots showing functionality on a simulator/emulator and assign to @patniemeyer and @theswerd when ready.

**Comment by advayDev1** [comment]
closes #1030

**Comment by patniemeyer** [comment]
@purpledrosophila This is a start but the code needs to be changed to use the HTML.  Right now the page expects the markdown style.   Let me know if you'd like me to take this part.

**Comment by purpledrosophila** [comment]
I might be able to help with that, but my specialty is in the writing; I'm
about 4 years out of professional programming. I'd rather leave that to
someone more experienced. Do you still want me to figure out how to put in
screenshots? I don't really know anything about emulators, so I'm not sure
if I could run the code properly. Is there any other HTML I can put in that
would be helpful, or are there any other files that I can help with writing
tweaks?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by patniemeyer** [comment]
@purpledrosophila Ok, let's close this and I'll take it.  Thanks for the effort.

**Comment by purpledrosophila** [comment]
@patniemeyer There are more inconsistencies in the HTML in this directory; I've gotten the go-ahead to fix them, and I figure I'll use the commit I was doing for this issue as a base, but is there any reason you can think of that I shouldn't change things right now? I think adding the simple HTML should be relatively trivial, but if I'm missing something, please let me know.

**Comment by patniemeyer** [comment]
@purpledrosophila I'll have to commit the HTML changes to "protect yourself" in conjunction with  changing the code that uses it.  (Otherwise it will not work).  If you have been asked to clean up the existing HTML in the other files please go ahead... It would probably be more appropriate to do it in a new PR though... thanks.

**Comment by purpledrosophila** [comment]
Does your code handle any of the other files in that directory, or just the
protect yourself one? If it could impact the others, I should probably wait
on the PR.

**Comment by patniemeyer** [comment]
All of the other files are already HTML and are independent.  So updating them is fine.  Thanks.

**Pull request closed without merging**
