### PR TITLE
Remove obsolete putDeviceToken and putLocation methods

### PR DESCRIPTION
**Pull request by matthewblain**
Remove obsolete putDeviceToken and putLocation methods.
The putClientSettings method should be used instead.

Completes the change described in Issue #1524

THIS SHOULD NOT BE MERGED UNTIL it is OK to obsolete old clients using the current methods.

## Screenshots

<details>
<summary>Screenshots</summary>
Add any relevant before/after screenshots here
</details>

## How did you test the change?

- [ ] iOS Simulator
- [ ] iOS Device
- [ ] Android Simulator
- [ ] Android Device
- [ ] `curl` to a dev App Engine server
- [ ] other, please describe

## Checklist:

- [ ] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md) and verified that all contributions are properly licensed pursuant to the [LICENSE](https://github.com/WorldHealthOrganization/app/blob/master/LICENSE).

### CODE REVIEW

**Comment by matthewblain** [comment]
Testing: Using an old client with a new server will cause the client to print out errors about unhandled exceptions. It will continue to run, though the server will not reflect the settings on the client.

**Review by brunobowden — APPROVED** [review]
Looks good but obviously hold off until the server is ready and updated.

The reference to issue #1502 seems to be in error.

**Review by theswerd — APPROVED** [review]

**Review by yukuairoy — APPROVED** [review]

**Comment by brunobowden** [comment]
We’re waiting on the other clients to get updated then we can merge this.

**Comment by matthewblain** [comment]
I think now is a good time to merge this in. Agree?

**Comment by brunobowden** [comment]
Please do.

**Pull request merged**
