### PR TITLE
Added a .nvmrc file so that nvm and asdf use the right node version

### LINKED ISSUE #171: What version of nodejs / npm is being assumed?
I'm assuming the latest LTS version as found here: https://nodejs.org/en/blog/

i.e. [nodejs version 12.16.1](https://nodejs.org/en/blog/release/v12.16.1/)

Is that a valid assumption?

### PR DESCRIPTION
**Pull request by RohanTalip**
## What does this PR accomplish?

Adds a client/ionic/.nvmrc file so that [nvm](https://github.com/nvm-sh/nvm) and [asdf](https://github.com/asdf-vm/asdf) use the right version of Node.js for local development.

Set the version of nodejs to the current LTS version of nodejs 10 (to match the current CI version), as found at https://nodejs.org/en/blog/ and https://nodejs.org/en/blog/release/v10.19.0/

(See also https://nodejs.org/download/release/latest-v10.x/ )

Closes #171

## Did you add any dependencies?

No.  [asdf](https://github.com/asdf-vm/asdf) is optional.

## How did you test the change?

n/a

### CODE REVIEW

**Comment by SamMousa** [comment]
I'd prefer to do this via `engines` in `package.json`: https://docs.npmjs.com/files/package.json

Since the node version is a dependency and we actually support a range, it makes no sense to  put 1 specific version in a tool specific configuration file imo.

Also, if we add both, shouldn't this file be in the ionic directory? Since the server side doesn't use node or might not use the same version.

I don't have a problem adding this both in `package.json` and via the `.tools-versions` file, but let's keep it local to the ionic client.

**Comment by hspinks** [comment]
@SamMousa I think `engines` is doing something pretty different than `asdf`. Still good to specify in our `package.json`, but `asdf` would automatically enforce everybody using the same node version (for those that use `asdf`), whereas if it's just in the `package.json`, it still relies on the developer choosing the right version.

I do agree with putting the `.tools-versions` file in the `client/ionic` directory

**Comment by hspinks** [comment]
@RohanTalip since `asdf` supports `.nvmrc` files and the only tool in the `client/ionic` dir right now is Node, how would you feel about using that syntax instead of `.tools-versions`? That way we'd cover all of the users who use NVM (very popular) as well as `asdf`

**Comment by SamMousa** [comment]
> @SamMousa I think `engines` is doing something pretty different than `asdf`. Still good to specify in our `package.json`, but `asdf` would automatically enforce everybody using the same node version (for those that use `asdf`), whereas if it's just in the `package.json`, it still relies on the developer choosing the right version.

Well not really, if we lock `npm engines` down to a specific version `npm install` won't work until you have that version.

I like @hspinks suggestion of `.nvmrc`, would that be ok for you?

**Comment by RohanTalip** [comment]
Done:
> * [x]  use `.nvmrc` instead of `.tool-versions` (since `asdf` respects `.nvmrc` too)
> * [x]  move that to the `client/ionic` directory

I added some documentation to the onboarding document too.

Feel free to squash the commits.  (I did consider creating a new PR since the branch no longer reflects exactly what is being changed, but I figured this one had context, so I kept it.)

Is it still necessary to add an `engines` specification to `package.json`?  If so, I can address that in a separate PR.

**Comment by advayDev1** [comment]
Thanks for the PR!  Per our discussion this morning, we are committed to Flutter for the client, so closing these out for now (since this is specific to use of node)

**Pull request closed without merging**
