### PR TITLE
Made localizations only take english for v01

### PR DESCRIPTION
**Pull request by theswerd**
## What does this PR accomplish?

Disabled non english localizations for v01 and left instructions for how to enable them

## How did you test the change?

iOS simulator

### CODE REVIEW

**Comment by SamMousa** [comment]
LGTM, though referencing an array like that is a bit brittle, for now it's fine.

**Comment by SamMousa** [comment]
Also just built this on android to confirm it still works.

**Comment by brunobowden** [comment]
@patniemeyer - PTAL

**Comment by theswerd** [comment]
@SamMousa @brunobowden now it calls english directly

**Comment by patniemeyer** [comment]
This is fine but alternately we could leave the localizations active but just remove the empty strings from the non-English files.  When a key is not found it should fall back to the base language.   The final translation will be done from the English / base file anyway so there is no need to put placeholder keys in the locale files.

**Comment by theswerd** [comment]
Is this PR outdated since we are past V01? @advayDev1

**Comment by advayDev1** [comment]
I like @patniemeyer 's plan better of fall back to base due to lack of key.

**Comment by advayDev1** [comment]
Closing - please go with @patniemeyer 's plan above.

**Pull request closed without merging**
