### PR TITLE
[ProtectYourself] adds Widget Test

### PR DESCRIPTION
**Pull request by AyushBherwani1998**
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the PR).**
- [x] Provided detailed pull request description and a succinct title (consider template below for guidance).
- [x] Tested your changes, especially after any code review iterations.
- [x] Included any relevant screenshots of UI updates.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Verified all contributions are properly licensed pursuant to the [LICENSE](https://github.com/WorldHealthOrganization/app/blob/master/LICENSE) file in the root of the repository.
- [x] Verified your name is in the [content/credits.yaml](https://github.com/WorldHealthOrganization/app/blob/master/content/credits.yaml) file (if you want it to be).

After all boxes above are checked, request and receive an Approved review from any team member knowledgable in the area (TODO team member list).  Once approved, the team member will assign your review to a Committer or use the `needs-merge` label.

## What does this PR accomplish?

Adds widget test for `ProtectYourself` page.
Fixes: #349

## Did you add any dependencies?
No

## How did you test the change?

Ran `flutter test` to run all the test.

### CODE REVIEW

**Comment by AyushBherwani1998** [comment]
@dnfield Can you help me the failing test. All of the tests are passed on the local machine. As of now, the test for WHO Myth-buster is also failing.

**Comment by dnfield** [comment]
Those tests are just broken right now.  There's no Image widget in the widget(s) it's testing, and there's no PageView anymore.

Probably someone changed the code and didn't update the test.

**Comment by dnfield** [comment]
https://github.com/WorldHealthOrganization/app/pull/474 fixes the tests.

**Comment by hspinks** [comment]
Closing since our UI is still changing rapidly

**Pull request closed without merging**
