### PR TITLE
[ci] Automatically label Issues that don't fill out checklist

### PR DESCRIPTION
**Pull request by hspinks**
Sets up a GitHub action to automatically label & comment on Issues whose checklists from the Issue templates are not already filled in. This will add the `resolved:missing-checklist` label if the checklist isn't followed. Hopefully this will encourage new contributors to follow the guidelines.

Note that as it's currently set up, it's looking for `- [ ]` to start a line, so it's not actually checking for the checklist items that are in the Issue templates. That means that if someone wants to include another checklist in an Issue, they would have to use the `* [ ]` to avoid being marked as missing a checklist. In the future, I plan on reading from the Issue templates to avoid this.

#### Did you add any dependencies?

This only adds dependencies to our GitHub Actions that respond to Issue events, so it doesn't touch the client or server code. It adds 2 official GitHub tools for Actions, [`@actions/core`](https://github.com/actions/toolkit/blob/master/packages/core) and [`@actions/github`](https://github.com/actions/toolkit/blob/master/packages/github). It adds [`@zeit/ncc`](https://github.com/zeit/ncc) as a dev dependency for compiling the action with its dependencies.

#### How did you test the change?

Since it's difficult to test GitHub Actions locally, I set up a separate repo to test my changes and created a few issues to see the automatic labeling happening.

---

#### Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the PR).
- [x] ~REQUIRED: Do you have an Issue **assigned to you** for this PR?~
- [x] Provided detailed pull request description and a succinct title
- [x] Tested your changes, especially after any code review iterations.
- [x] ~Included any relevant screenshots of UI updates.~
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Verified all contributions are properly licensed pursuant to the [LICENSE](https://github.com/WorldHealthOrganization/app/blob/master/LICENSE) file in the root of the repository.
- [x] Verified your name is in the [content/credits.yaml](https://github.com/WorldHealthOrganization/app/blob/master/content/credits.yaml) file (if you want it to be).

### CODE REVIEW

**Comment by advayDev1** [comment]
Opened 5hrs ago.... 🤔

**Comment by SamMousa** [comment]
I think this is a lot of code to be pushing all into the `.github` folder.
Imo this should be refactored into a separate github action that does not live in this repo.

**Comment by hspinks** [comment]
> I think this is a lot of code to be pushing all into the .github folder.
> Imo this should be refactored into a separate github action that does not live in this repo.

@SamMousa that is precisely why this is a draft PR 😉 

I had a quick chat with @advayDev1 about where this should live in general, but very curious to hear your thoughts as well. The options as I see it are:
* Extracted into a personal `hspinks/issue-checklist-checker` and published as a separate, standalone GitHub Action (downside is that governance would be separate from this app project, and updates would need to be submitted to my personal repo)
* Extracted into a WHO-owned repo and published as a separate, standalone GitHub Action (downside is governance and commitment to maintaining it as an OS project, or how to clearly label that it is not a maintained OS project outside of this app)
* Extracted into a WHO-owned repo and imported into this repo by some mechanism other than a standard GitHub Action (e.g. git submodule)

I've left this PR open as a draft until we think through how we want to solicit feedback on this code, which I believe should be reviewed (at least initially) by contributors to this repo regardless of where it ultimately lives.

**Comment by SamMousa** [comment]
I think option one or two are both fine. Note that it will be maintained and if others decide to use it then they can submit PRs to improve it.

**Pull request closed without merging**
