### PR TITLE
Ionic sample

### PR DESCRIPTION
**Pull request by SamMousa**
This is an alternative to react-native based on discussion in #7.

Having not worked with either of the stacks I found the ionic stack way more accessible, both for building the webbased as well as the android app.

In this example I have also integrated the survey library I mentioned in #1. In that discussion there was also a mention of using [react-jsonschema-form](https://github.com/rjsf-team/react-jsonschema-form).
I imagine that this will be just as simple to integrate.

This is not meant to be merged unless we actually decide to switch to the ionic stack.

### CODE REVIEW

**Comment by advayDev1** [comment]
Decisions from this morning: This will be the earliest iteration.   Get it reviewed and checked in, to be adapted by @SamMousa and @pat (username unknown) for static 0.1.

**Comment by advayDev1** [comment]
Sam, what parts of this are hand-coded, and what parts are auto-gened templates?  Is all the stuff being put in compatibly licensed?

**Comment by SamMousa** [comment]
This is all generated by ionic cli, which is MIT. My edits are the content addition of survey-react which is also MIT (I think, check out SurveyJS library)

**Comment by advayDev1** [comment]
Closing this in favor of 41

**Pull request closed without merging**
