### PR TITLE
Remove unused code

### PR DESCRIPTION
**Pull request by theswerd**
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the PR).**
- [ ] REQUIRED: Do you have an Issue **assigned to you** within the v1 milestone for this PR?  Put the Issue number here:
- [ ] Provided detailed pull request description and a succinct title (consider template below for guidance).
- [x] Tested your changes, especially after any code review iterations.
- [ ] Included any relevant screenshots of UI updates.
- [ ] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [ ] Verified all contributions are properly licensed pursuant to the [LICENSE](https://github.com/WorldHealthOrganization/app/blob/master/LICENSE) file in the root of the repository.
- [ ] Verified your name is in the [content/credits.yaml](https://github.com/WorldHealthOrganization/app/blob/master/content/credits.yaml) file (if you want it to be).

After all boxes above are checked, request and receive an Approved review from any team member knowledgable in the area (TODO team member list).  Once approved, the team member will assign your review to a Committer or use the `needs-merge` label.

## What does this PR accomplish?

Removes the unused code
- delete who_myth_busters.dart because it is outdated and no longer used
- delete emojiHeader because it is only used in who_myth_busters.dart
- delete who myth buster tests because they will alway pass as they are testing  who_myth_busters.dart(no longer used)
- delete flutter test CI file because it is running tests that don't test anything

Outcomes:
- Smaller, easier to read codebase
     - Smaller bundle size
- Faster CI

## Did you add any dependencies?

No

## How did you test the change?

- iOS simulator
- Seeing if this passes the CI

### CODE REVIEW

**Comment by epicfaace** [comment]
I think you should also remove the yaml files from https://github.com/WorldHealthOrganization/app/tree/master/client/flutter/assets/content_bundles and close #683.

**Comment by theswerd** [comment]
Im going to add it back without the final ine

**Comment by theswerd** [comment]
Add flutter format to CI
Closes #334

**Comment by epicfaace** [comment]
@theswerd for some reason the build is failing now -- `Could not find an option named "pub".`.

I think it might be best for now to move the format changes to a separate PR, especially because I don't know if we want to have that in before v1.0 (I remember some discussion earlier about potentially leaving formatting changes to after v1.0)

**Comment by theswerd** [comment]
@epicfaace It works now

**Comment by epicfaace** [comment]
@theswerd at this point, I think it might be best to break up this PR into two ones -- one that removes the unused code, and another that does the format. Given the large number of PRs that are going in / need to be reviewed, it might be better to do the format at a later time so that it doesn't hold up all the other PRs (since you would have to rebase those PRs)

**Pull request closed without merging**
