### PR TITLE
added chevrons

### LINKED ISSUE #999: Design Review: Get the Facts - Instead of a "Next Fact" text button use a chevron next to the page indicators
cc @davidkaneda

### PR DESCRIPTION
**Pull request by theswerd**
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the PR).**
- [ ] REQUIRED: Do you have an Issue **assigned to you** within the v1 milestone for this PR?  Put the Issue number here:
- [ ] Provided detailed pull request description and a succinct title (consider template below for guidance).
- [ ] Tested your changes, especially after any code review iterations.
- [ ] Included any relevant screenshots of UI updates.
- [ ] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [ ] Verified all contributions are properly licensed pursuant to the [LICENSE](https://github.com/WorldHealthOrganization/app/blob/master/LICENSE) file in the root of the repository.
- [ ] Verified your name is in the [content/credits.yaml](https://github.com/WorldHealthOrganization/app/blob/master/content/credits.yaml) file (if you want it to be).

After all boxes above are checked, request and receive an Approved review from any team member knowledgable in the area (TODO team member list).  Once approved, the team member will assign your review to a Committer or use the `needs-merge` label.

## What does this PR accomplish?

Added chevrons to app Get the Facts page

Closes #999

## Did you add any dependencies?

No

## How did you test the change?

iOS simulator
Simulator Screen Shot - iPhone 11 Pro - 2020-04-13 at 11 49 54

### CODE REVIEW

**Comment by patniemeyer** [comment]
This question was raised at the meeting this morning but - I'm not sure what the design wants as far as the page indicator position goes.  If the page indicator gets more padding below then it should probably be vertically centered with the chevrons.

**Comment by davidkaneda** [comment]
Yes, please vertically center with the chevrons (raise the indicator row). Could we also use the lighter blue for the chevron arrows (#008DC9), and a light gray for the inactive indicator dots (#d8d9da)? Just to confirm, do the chevrons go away when at one end of the carousel (ie. no back when you're at the first dot)? Think I'd lean this way-

Many thanks!

**Comment by theswerd** [comment]
Simulator Screen Shot - iPhone 11 Pro - 2020-04-14 at 11 32 52
Centers

**Comment by davidkaneda** [comment]
Alignment lg!

**Pull request merged**
