### PR TITLE
Changed Home Page

### PR DESCRIPTION
**Pull request by jasonTelanoff**
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the PR).**
- [x] Provided detailed pull request description and a succinct title (consider template below for guidance).
- [x] Tested your changes, especially after any code review iterations.
- [x] Included any relevant screenshots of UI updates.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Verified all contributions are properly licensed pursuant to the [LICENSE](https://github.com/WorldHealthOrganization/app/blob/master/LICENSE) file in the root of the repository.
- [x] Verified your name is in the [content/credits.yaml](https://github.com/WorldHealthOrganization/app/blob/master/content/credits.yaml) file (if you want it to be).

After all boxes above are checked, request and receive an Approved review from any team member knowledgable in the area (TODO team member list).  Once approved, the team member will assign your review to a Committer or use the `needs-merge` label.

## What does this PR accomplish?

Changes Home Page layout

Added a staggered grid view layout.

## Did you add any dependencies?

flutter_staggered_grid_view: ^0.3.0

## How did you test the change?

I ran the app on physical android device with no issues.
Screenshot_20200327-130338

### CODE REVIEW

**Comment by patniemeyer** [comment]
Two trivial things: IDE is complaining about repeating the const keyword on the StageredTile list and the use of the "new" keyword below.   Not blockers but if you have a sec to remove.

**Comment by patniemeyer** [comment]
The line break in "Your Questions Answered" is tricky... We can break it manually by inserting a newline but not sure that's the right thing to do.  Maybe add the newline and let's ask one of the other devs to take this specific issue.

**Comment by theswerd** [comment]
@patniemeyer we can wrap it in a center and set the textAlign to center

**Comment by patniemeyer** [comment]
Ah, misread that it was already centered and not working.  Great!

**Comment by patniemeyer** [comment]
@jasonTelanoff If you could add `textAlign: TextAlign.center` on those page buttons and maybe do a quick cleanup pass to remove the old commented code, etc. I'll merge this!

**Pull request merged**
