### PR TITLE
Fixes page header content layout to avoid overflow on smaller screens

### PR DESCRIPTION
**Pull request by Samaritan1011001**
This PR fixes a known issue documented in #651 with the use of Flutter's widgets such as Flexible, SizedBox and FittedBox

- [ ] REQUIRED: Do you have an Issue **assigned to you** within the v1 milestone for this PR?  Put the Issue number here: #651 but Not assigned to me but I found a fix
- [x] Provided detailed pull request description and a succinct title (consider template below for guidance).
- [x] Tested your changes, especially after any code review iterations.
- [x] Included any relevant screenshots of UI updates.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Verified all contributions are properly licensed pursuant to the [LICENSE](https://github.com/WorldHealthOrganization/app/blob/master/LICENSE) file in the root of the repository.
- [x] Verified your name is in the [content/credits.yaml](https://github.com/WorldHealthOrganization/app/blob/master/content/credits.yaml) file (if you want it to be).

After all boxes above are checked, request and receive an Approved review from any team member knowledgable in the area (TODO team member list).  Once approved, the team member will assign your review to a Committer or use the `needs-merge` label.

## What does this PR accomplish?
This PR fixes an overflow issue in the page header of all the screens. Flutter widgets used -

- Flexible is used to allow the text component of the header take up the space available rather than a whole block of space in the header.

- FittedBox helps with preserving the scale factor of the text when the screen size varies

- SizedBox is used to create a gap between the text and the WHO symbol and is dynamic in layout size as well with a min width of 5.0

## Did you add any dependencies?
No

## How did you test the change?
I tested it on 

- Android Nexus S of 4 inches

Screenshot_1585625600

- Android Pixel 3a 5.6 inches

Screenshot_1585625576

- Chrome 

Screenshot (9)

### CODE REVIEW

**Comment by Samaritan1011001** [comment]
@patniemeyer Please, take a look at this when you can. Thanks!

**Comment by Samaritan1011001** [comment]
@theswerd I resolved the conflict and it's now ready
I am new here so I was wondering who can accept this PR? 
Thanks for having a look

**Comment by Samaritan1011001** [comment]
Any update on this PR?

**Comment by patniemeyer** [comment]
looking again now.

**Comment by patniemeyer** [comment]
@Samaritan1011001 Thank you for this. I approved but there are now some conflicts (sorry for the slow approval)

**Comment by Samaritan1011001** [comment]
@patniemeyer Thank you for approving this! I am following the developments closely and I'll be around if you need a hand with anything

**Pull request merged**
