### PR TITLE
App icons

### PR DESCRIPTION
**Pull request by crazybob**

### CODE REVIEW

**Comment by advayDev1** [comment]
Can you check them in to `/identity` where the LICENSE labels them not MIT Licensed?  We've been symlinking them in where needed in the client.

**Comment by advayDev1** [comment]
Also see https://github.com/WorldHealthOrganization/app/pull/189

**Comment by crazybob** [comment]
I moved them and them moved them back. Are you sure? These are iOS-specific icons that I created.

**Comment by advayDev1** [comment]
Its what we've been doing elsewhere.  We submit them in `identity/' and symlink them from wherever they are used.   Ursula from WHO approved the following license text previously until they can give further guidance:
```
The WHO visual identity assets in identity/, including but not limited to the
WHO Logo and Emblem, are not licensed under the MIT License and are instead
subject to the policies at
https://www.who.int/about/who-we-are/publishing-policies/copyright
and
https://www.who.int/about/who-we-are/publishing-policies/logo .
```

**Comment by advayDev1** [comment]
The Flutter directory has its own icons, closing for now.

**Pull request closed without merging**
