### PR TITLE
Re-add triage

### PR DESCRIPTION
**Pull request by SamMousa**
## What does this PR accomplish?
It implements the survey created by @pjayathissa.

- This does not add a link to the menu for triage, so it is essentially a feature that is currently off.

#178 
#148 

## Did you add any dependencies?
No

## How did you test the change?
On web, by going to `/triage`, as well as on android by modifying a link in the menu temporarily.

### CODE REVIEW

**Comment by myiremark** [comment]
I'm good with this, but I think we intended to leave stuff at design spec until after v0.1

**Comment by SamMousa** [comment]
I'll leave this here then.

**Comment by pjayathissa** [comment]
@SamMousa This looks good to me. And even if we don't add the name in the menu bar I can still use the live link to test it with local medical experts.

Are you going to add the triage to the menu so that the WHO team can easily access it? We could probably call it `Check your health (beta)` or something so that they know that it is not final?

**Comment by SamMousa** [comment]
> Are you going to add the triage to the menu so that the WHO team can easily access it? 

I'm not doing any more commits tonight, so no :) 

--> if we want that someone can add it, but let's not do that for v0.1

**Comment by pjayathissa** [comment]
> > Are you going to add the triage to the menu so that the WHO team can easily access it?
> 
> I'm not doing any more commits tonight, so no :)
> 
> --> if we want that someone can add it, but let's not do that for v0.1

Sounds good to me. Sleep well

**Pull request merged**
