### PR TITLE
Fixed spelling mistake of "cougningAndSneezing"

### PR DESCRIPTION
**Pull request by danielwilliamson**
## What does this PR accomplish?

Fixes a spelling mistake with the localization.

There was a spelling mistake with the localisation key `cougningAndSneezing` it has now been correctly updated to `coughingAndSneezing`

## Did you add any dependencies?

N/A

## How did you test the change?

- Regenerated i10n files
- Ran the client project successfully

- [x] Provided detailed pull request description and a succinct title (consider template below for guidance).
- [x] Tested your changes, especially after any code review iterations.
- [x] Included any relevant screenshots of UI updates.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Verified all contributions are properly licensed pursuant to the [LICENSE](https://github.com/WorldHealthOrganization/app/blob/master/LICENSE) file in the root of the repository.
- [x] Verified your name is in the [content/credits.yaml](https://github.com/WorldHealthOrganization/app/blob/master/content/credits.yaml) file (if you want it to be).

### CODE REVIEW

**Comment by advayDev1** [comment]
Hey @danielwilliamson  can you make sure your Git commit email address is in GitHub?  Please amend the commit once configured.

**Comment by danielwilliamson** [comment]
@advayDev1 That should be fixed now.

**Comment by advayDev1** [comment]
We just updated our contribution guidelines.  Please copy the below in your own PR description.
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the PR).**
- [ ] Provided detailed pull request description and a succinct title (consider template below for guidance).
- [ ] Tested your changes, especially after any code review iterations.
- [ ] Included any relevant screenshots of UI updates.
- [ ] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [ ] Verified all contributions are properly licensed pursuant to the [LICENSE](https://github.com/WorldHealthOrganization/app/blob/master/LICENSE) file in the root of the repository.
- [ ] Verified your name is in the [content/credits.yaml](https://github.com/WorldHealthOrganization/app/blob/master/content/credits.yaml) file (if you want it to be).

After all boxes above are checked, request and receive an Approved review from any team member knowledgable in the area (TODO team member list).  Once approved, the team member will assign your review to a Committer or use the `needs-merge` label.

**Comment by SamMousa** [comment]
Please resolve conflicts!

**Comment by danielwilliamson** [comment]
Conflicts should now be resolved

**Comment by advayDev1** [comment]
This key is unused

**Pull request closed without merging**
