### PR TITLE
[WHO Myth-buster] adds Widget Test

### LINKED ISSUE #351: [who_myth_busters.dart] add automated tests
https://github.com/WorldHealthOrganization/app/issues/342

### PR DESCRIPTION
**Pull request by AyushBherwani1998**
## What does this PR accomplish?
Adds widget test for WHO myth-buster page. Fixes  #351

## Did you add any dependencies?
No new dependencies added.

## How did you test the change?
Ran `flutter test` command to run the test.

### CODE REVIEW

**Comment by PieterAelse** [comment]
Hmm, this looks a bit more of an integration test as `MyApp` is used, instead of the `WhoMythBusters` widget itself.
Why not just pump `WhoMythBusters` widget and test this specifically. Other tests (integration) should test the "routing" from homepage to this widget.

**Comment by AyushBherwani1998** [comment]
> Why not just pump `WhoMythBusters` widget and test this specifically. Other tests (integration) should test the "routing" from homepage to this widget.

Actually, if I'll directly pump the `WhoMythBuster` then it will throw the error because of `AppLocalizationDelegate`. To avoid this, I have two options, either wrap `WhoMythBusters` with `MaterialApp` or pump `MyApp` and do the routing. 

I opted for the second one because it also ensured that the routes are working properly. But I guess, it creates confusion.

**Comment by SamMousa** [comment]
@patniemeyer @dnfield what is your opinion? On the choice made  (see comments above)

**Comment by SamMousa** [comment]
@AyushBherwani1998 please add your name to the credits file (or let us know if you don't want to be in there via a post here)

**Comment by AyushBherwani1998** [comment]
@SamMousa the recent commit of flutter analyzer has found some issues in the repo. I'm solving it and pushing a new commit.

**Comment by SamMousa** [comment]
This is blocked by #399.

Side note, could you run `flutter format` on the changed files? Just to be sure we don't break stuff again when #396 gets merged.

**Pull request merged**
