### PR TITLE
Stop refreshing page on navigation by replacing href with routerLink

### PR DESCRIPTION
**Pull request by epicfaace**
Using `href` will refresh the entire page upon navigation, as you can see on the example app. Really, we should be using a `Link` component from react-router to navigate to different pages without necessitating a page refresh.

Since we are using `IonItem` / `IonButton`, we can also pass in the link to the `routerLink` prop to have this same behavior. See https://ionicframework.com/docs/react/navigation#navigation

### CODE REVIEW

**Comment by SamMousa** [comment]
Visual code inspection LGTM.
I can't build it locally at the moment, if someone can and confirms it works I'll merge this.

**Comment by SamMousa** [comment]
@myiremark if you can confirm this work I'll merge it.

**Comment by advayDev1** [comment]
Just to remind how the PRs work.  You've chosen to assign this PR to me and @myiremark , so neither sam nor i would merge your CL in until me and mark have LGTMed

**Comment by SamMousa** [comment]
I assigned it to Mark since he was looking for work ; I couldn't test locally other than visual code inspection, hence my comment.

**Pull request merged**
