### PR TITLE
Fix for issue #1350

### LINKED ISSUE #1350: On small screens, intro text is left aligned
What's happening here is the text widget is centered in the container, but the widget's own text alignment is left.

iPhone 8:

Simulator Screen Shot - iPhone 8 - 2020-05-23 at 17 55 02

### PR DESCRIPTION
**Pull request by cosmicRover**
(attempt #2) Dynamically adjusts Font Size based on screen width and platform.
Closes #1350 

```
if (Platform.isAndroid) {
      if (screenWidth > 320) {
        return 18;
      } else {
        return 16;
      }
    } else if (Platform.isIOS) {
      if (screenWidth > 375) {
        return 18;
      } else if (screenWidth <= 320) {
        return 14;
      } else {
        return 16;
      }
    }
    return 18;
  }
``` 

#### Tested on:
* [x] iOS Simulator
* [x] Android Emulator
* [ ] iOS Device
* [ ] Android Device
* [ ] `curl` to a dev App Engine server

### CODE REVIEW

**Comment by mohak852** [comment]
You can just wrap it under fittedBox. This is not required and it will fix this

**Comment by cosmicRover** [comment]
> You can just wrap it under fittedBox. This is not required and it will fix this

Oh I apologize. Do you want me to make the change or it's no longer necessary?

**Comment by mohak852** [comment]
> > You can just wrap it under fittedBox. This is not required and it will fix this
> 
> Oh I apologize. Do you want me to make the change or it's no longer necessary?

I have committed the changes and they are about to merge my changes well thank you for this contribution you can see any other issues.

@cosmicRover

**Comment by cosmicRover** [comment]
Yessir!

**Comment by cosmicRover** [comment]
fixed

**Pull request closed without merging**
