### PR TITLE
Fix Ink bug & refactor to adhere to Flutter format and style

### PR DESCRIPTION
**Pull request by creativecreatorormaybenot**
## What does this PR accomplish?

This PR **fixes** an ink bug with the close button for `CarouselSlide`s. You can see screenshots below.

Additionally, I refactored code.

### Why refactor in the same PR?

Not applying format changes in this PR would cause many problems and it is not really suitable to separate format changes from other code changes. 

### What guidelines does the refactor follow?

I did two things: `flutter format .` in the `client` directory, which will apply Flutter's format. Additionally, I converted *double quotes* to **single quotes**. [See Flutter's Style Guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#prefer-single-quotes-for-strings).  
Because of this, #362 should probably be merged first.

### Minor changes

`Alignment` should be used for `Align`. Furthermore, types can be omitted when variables are implicitly typed. There was one line using `double` and the next using `var`. They could both be combined to use `var`.

Moreover, I added `pubspec.lock` to `.gitignore` and removed the file because it would be changed by every build of the app and with every commit, which should be avoided.

## Did you add any dependencies?

**No**.

## How did you test the change?

<details>
<summary>Screenshots of the ink UI fix</summary>

Before I fixed the ink issue of the close button:

![Before][]

After:

![After][]
</details>

 [Before]: https://i.imgur.com/FAjkFg8.png
 [After]: https://i.imgur.com/VMTIu2u.png

### CODE REVIEW

**Comment by epicfaace** [comment]
Are the format changes in this PR the same as those in #362? If so, could you remove the format changes in this PR so we only have one PR with format changes in it?

**Comment by creativecreatorormaybenot** [comment]
@epicfaace I addressed this in the original comment.. I also explained why, but I can try to explain it again for you; maybe it will be clearer.

The format changes are the same. They just *happen* when running `flutter format . --fix` and I ran that because I changed some code.  
The solution to this is to merge #362, then the changes here will *disappear*.

**Comment by SamMousa** [comment]
Closing this since it combines a bugfix and a large refactoring.
The refactoring is handled by #362.

**Comment by creativecreatorormaybenot** [comment]
@SamMousa So, should I open another PR or what?

What open source guidelines are you following? I am bit confused by 
how you are handling PRs.

**Comment by SamMousa** [comment]
Please make sure there is an issue first, so that we can actually assign it and prevent double work. I'm handling PRs as best I can but as you can see in the list of PRs created just today we're getting lots of duplicates.

This PR does 2 things one of which is a big refactor, this makes it hard to review.
If you want to file an issue for the ink bug please go ahead and I'll assign it to you so you can create a fix for that.

**Comment by creativecreatorormaybenot** [comment]
@SamMousa I see.

**Pull request closed without merging**
