### PR TITLE
Add French (fr-FR) translation

### PR DESCRIPTION
**Pull request by jjerphan**
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the PR).**
- [x] Provided detailed pull request description and a succinct title (consider template below for guidance).
- [x] Tested your changes, especially after any code review iterations.
- [x] Included any relevant screenshots of UI updates.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Verified all contributions are properly licensed pursuant to the [LICENSE](https://github.com/WorldHealthOrganization/app/blob/master/LICENSE) file in the root of the repository.
- [x] Verified your name is in the [content/credits.yaml](https://github.com/WorldHealthOrganization/app/blob/master/content/credits.yaml) file (if you want it to be).

After all boxes above are checked, request and receive an Approved review from any team member knowledgable in the area (TODO team member list).  Once approved, the team member will assign your review to a Committer or use the `needs-merge` label.

## What does this PR accomplish?

Adds a French translation
Adds new entries have been add according to the original English version.

**Design discussion**

The original meaning might be different from the original one for some phrases.

For example:
 - if sustained language has to be used, the `whoMythBusters` entry might be to change.
 - if the imperative mood has to be used, some entries have to be changed as well.

Hence some wording has to be discussed to express the exact message.

This relates to #224.

## Did you add any dependencies?

No.

## How did you test the change?

I'm relying on the CI tests only.

### CODE REVIEW

**Comment by orchardbirds** [comment]
Also, I think you need to add to  `messages_fr.dart` in `app/client/flutter/lib/generated/intl/`

**Comment by jjerphan** [comment]
Thanks for the review.

> Also, I think you need to add to messages_fr.dart in app/client/flutter/lib/generated/intl/

@orchardbirds: I've seen this file too, but by looking at the first line, it looks like it has been generated from its counterpart in `client/flutter/lib/generated/intl`:
```dart
// DO NOT EDIT. This is code generated via package:intl/generate_localized.dart
```

**Comment by gcarmix** [comment]
> Thanks for the review.
> 
> > Also, I think you need to add to messages_fr.dart in app/client/flutter/lib/generated/intl/
> 
> @orchardbirds: I've seen this file too, but by looking at the first line, it looks like it has been generated from its counterpart in `client/flutter/lib/generated/intl`:
> 
> ```dart
> // DO NOT EDIT. This is code generated via package:intl/generate_localized.dart
> ```

You are right, I had this problem too for italian, then had it to automatically generate the contents by adding intl_translation like suggested in the comments of #401

**Comment by sapte91** [comment]
@jjerphan Thank you so much for your support of this project and for the time you spent on this PR - we’re so humbled by your willingness to jump in! We have an important update on localization for the application: We’ll primarily be sourcing and managing translations from Lingo24, our translation management system. Also, our designs changed, so these translations are now out of date. As such, I’m closing this PR.

We will still need translation volunteers - as our set of supported languages and locales grows, there will be plenty of opportunity to contribute! Our projected needs for the next two months are in native speaker LQA and translations for languages that we cannot support on Lingo24. We apologize that we are still in the early process of figuring out how to manage all the contributions and will have more details soon. Until then, please fill out the volunteer form below and we’ll get back in touch shortly.

https://forms.gle/DTqvaqh4mE7bDe5U7

**Pull request closed without merging**
