### PR TITLE
Component borders weren't being shown via TalkBack on Android.

### PR DESCRIPTION
**Pull request by britannio**
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the PR).**
- [x] REQUIRED: Do you have an Issue **assigned to you** within the v1 milestone for this PR?  Put the Issue number here: https://github.com/WorldHealthOrganization/app/issues/935
- [x] Provided detailed pull request description and a succinct title (consider template below for guidance).
- [x] Tested your changes, especially after any code review iterations.
- [x] Included any relevant screenshots of UI updates.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Verified all contributions are properly licensed pursuant to the [LICENSE](https://github.com/WorldHealthOrganization/app/blob/master/LICENSE) file in the root of the repository.
- [x] Verified your name is in the [content/credits.yaml](https://github.com/WorldHealthOrganization/app/blob/master/content/credits.yaml) file (if you want it to be).

After all boxes above are checked, request and receive an Approved review from any team member knowledgable in the area (TODO team member list).  Once approved, the team member will assign your review to a Committer or use the `needs-merge` label.

## What does this PR accomplish?
- Closes https://github.com/WorldHealthOrganization/app/issues/935
- Reverts to the old flutter embedding system(I believe) which doesn't have this issue. I'm not aware of any drawbacks to this.

## Did you add any dependencies?
No

## How did you test the change?

No green outline was being shown previously, now it works as expected.
Screenshot_20200407-202644

### CODE REVIEW

**Comment by advayDev1** [comment]
Can you explain in the PR description how your changes achieve the fix?

**Comment by britannio** [comment]
> Can you explain in the PR description how your changes achieve the fix?

Done. I did it initially, checked the box then changed the code and forgot to replace the message 🤦

**Comment by advayDev1** [comment]
Let's get some more feedback on this.  @dnfield is this the right thing to do?

**Comment by dnfield** [comment]
@blasten @xster are you familiar with this?

/cc @matthew-carroll @mklim as well who may know.

**Pull request merged**
