### PR TITLE
Fix close button Ink

### LINKED ISSUE #432: CarouselSlide close button Ink is on the wrong surface
The ink of the close button of every `CarouselSlide` is covered by the content `Card` **below** it. This should not be the case.

![screenshot][]

 [screenshot]: https://i.imgur.com/FAjkFg8.png

### PR DESCRIPTION
**Pull request by creativecreatorormaybenot**
- [x] Provided detailed pull request description and a succinct title (consider template below for guidance).
- [x] Tested your changes, especially after any code review iterations.
- [x] Included any relevant screenshots of UI updates.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Verified all contributions are properly licensed pursuant to the [LICENSE](https://github.com/WorldHealthOrganization/app/blob/master/LICENSE) file in the root of the repository.
- [x] Verified your name is in the [content/credits.yaml](https://github.com/WorldHealthOrganization/app/blob/master/content/credits.yaml) file (if you want it to be).

## What does this PR accomplish?

Fixes #432.

Additionally, I properly used `Alignment` for the button.

## Did you add any dependencies?

**No**.

## How did you test the change?

<details>
<summary>Screenshots of the ink UI fix</summary>

Before I fixed the ink issue of the close button:

![Before][]

After:

![After][]
</details>

 [Before]: https://i.imgur.com/FAjkFg8.png
 [After]: https://i.imgur.com/VMTIu2u.png

### CODE REVIEW

**Comment by creativecreatorormaybenot** [comment]
@SamMousa I fixed it now. I am not sure if you will like how complicated this is, but there is not an easier way AFAIC.

**Comment by SamMousa** [comment]
Thanks!

>  I am not sure if you will like how complicated this is, but there is not an easier way AFAIC.

I'll wait for a skilled flutter dev to do a code review. @patniemeyer @theswerd @kassim could one of you review the code? (Or anyone else with flutter experience)

This works on my android phone.

**Comment by creativecreatorormaybenot** [comment]
@SamMousa There was an "interesting" test that checked if there was only one image (not sure why that would be a good test, but I did not want to remove it).

The solution to this was to change this test to use a semantics label instead. Now, there is another problem: I think that this semantics label is actually valuable because it will aid people that need to use TalkBack etc. However, this string needs to be localized. How would I go about doing that?

**Comment by patniemeyer** [comment]
Hi everyone.  Thanks for working on this but I'd really like to hold off on the UI fixes until we have an updated design (which I'm hoping we'll get get today).  For all we know this may completely change.  The work looks good.  I suspect, as you did, that there may be another approach to this but I'm not overly worried about that.  I'd just like to see where we're going with this today.  Thanks!

**Comment by patniemeyer** [comment]
> @SamMousa There was an "interesting" test that checked if there was only one image (not sure why that would be a good test, but I did not want to remove it).
> 
> The solution to this was to change this test to use a semantics label instead. Now, there is another problem: I think that this semantics label is actually valuable because it will aid people that need to use TalkBack etc. However, this string needs to be localized. How would I go about doing that?
> 
> Otherwise, I can also remove the test.

@SamMousa  In the same spirit as my other comment I'd really suggest that we hold off on UI testing at this time (at least anything that would block a merge).  We are so far away from having a meaningfully solid design and the application is so simple and has so many eyes on it right now that I just don't think we should spend any of your valuable time on that aspect yet.

**Comment by patniemeyer** [comment]
@creativecreatorormaybenot Thank you for your time and work on this but the new design no longer includes the carousel so I'm going to close this for now.

**Pull request closed without merging**
