### PR TITLE
Add scripts to swap in prod firebase config before cutting a release branch

### PR DESCRIPTION
**Pull request by epicfaace**
## What does this PR accomplish?

deploy-prod.sh can be run right before cutting a release branch so that the right
firebase config can be swapped in. We can also modify this to make other changes
that may need to be modified from dev -> prod.

for #730

### CODE REVIEW

**Comment by hspinks** [comment]
I really like this idea of having a script to automate these tasks to avoid any possible human error on this. Where did we shake out on the conversation of including these files in the repo in general?

**Comment by epicfaace** [comment]
> I really like this idea of having a script to automate these tasks to avoid any possible human error on this. Where did we shake out on the conversation of including these files in the repo in general?

These files are already included in the repo, as part of the RC branch, so it should be fine to keep them in the repo.

It's good to keep them in the repo so that they can be version-controlled and the appropriate flags / settings are also included in version control.

**Comment by hspinks** [comment]
I think that what's implemented here is exactly right for a pre-deploy process/hook, but I think this should be held until the multi-repo flow proposed in #854 is implemented, since this script & the prod config files should be in the `app-private` repo. I'm moving this out of the `v1.0` milestone since this isn't necessary for launch - our existing manual process can work fine if this isn't merged by then.

> These files are already included in the repo, as part of the RC branch, so it should be fine to keep them in the repo.

These files aren't sensitive, which is why it's ok to be in the RC branch. But it's still a little bit better to make someone dig for them than to put them in `master` where every single person forking the repo has those files in their working copy. This won't stop someone who really wants to find those config files, but this isn't a huge security concern. Since the prod build will happen in the `app-private` repo anyway to make sure the proper assets are included, it makes sense for this pre-deploy script to be there, too.

**Comment by hspinks** [comment]
I'm going to close this, since the prod firebase config can be included in the overlay repo as proposed in #854

**Pull request closed without merging**
