### PR TITLE
Fixed icon click effect in PageScaffold

### PR DESCRIPTION
**Pull request by Moosphan**
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the PR).**
- [ ] REQUIRED: Do you have an Issue **assigned to you** within the v1 milestone for this PR?  Put the Issue number here:
[#603 ]（https://github.com/WorldHealthOrganization/app/issues/603）
- [x] Provided detailed pull request description and a succinct title (consider template below for guidance).
- [x] Tested your changes, especially after any code review iterations.
- [x] Included any relevant screenshots of UI updates.
Here is the screenshot on my phone (One plus 7T pro - *Android 10*)
  
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Verified all contributions are properly licensed pursuant to the [LICENSE](https://github.com/WorldHealthOrganization/app/blob/master/LICENSE) file in the root of the repository.
- [ ] Verified your name is in the [content/credits.yaml](https://github.com/WorldHealthOrganization/app/blob/master/content/credits.yaml) file (if you want it to be).

After all boxes above are checked, request and receive an Approved review from any team member knowledgable in the area (TODO team member list).  Once approved, the team member will assign your review to a Committer or use the `needs-merge` label.

## What does this PR accomplish?
Fixed the problem that the leading area still has responsive click effect in `SliverAppBar`.

## Did you add any dependencies?
No.

## How did you test the change?
Based on CI tests and ran on my phone.

### CODE REVIEW

**Comment by britannio** [comment]
https://github.com/WorldHealthOrganization/app/pull/568#discussion_r399855484
I propose this change before the troubled commit was merged.

**Comment by Moosphan** [comment]
@britannio Yeah, but the first way that changed icon color caused the problem on that screenshot,   
 I agree with you with the second way.

**Comment by britannio** [comment]
What are the last two commits for?

**Comment by Moosphan** [comment]
@britannio Just resolved conflicts, and you can ignore this.

**Comment by britannio** [comment]
client/flutter/lib/generated/i18n.dart
client/flutter/pubspec.lock
and client/flutter/res/values/strings_en.arb
Don't seem like they needed to be changed to fix the bug

**Comment by Moosphan** [comment]
@britannio Oh, that's my fault, I will fix this.

**Comment by britannio** [comment]
Only 1 file should've changed and that's `client/flutter/lib/components/page_scaffold.dart`

**Comment by Moosphan** [comment]
@britannio What's about now?

**Pull request merged**
