### PR TITLE
Remove vscode settings

### PR DESCRIPTION
**Pull request by theswerd**
# Remove Vscode settings

I'm relatively confident the VSCode settings were committed by accident. They have also caused problems for me, and for other VSCode developers working on the client because they hide the client directory.

## Checklist:

- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md) and verified that all contributions are properly licensed pursuant to the [LICENSE](https://github.com/WorldHealthOrganization/app/blob/master/LICENSE).

### CODE REVIEW

**Comment by theswerd** [comment]
@advayDev1 can you confirm these were committed by accident?

**Review by yukuairoy — APPROVED** [review]

**Comment by brunobowden** [comment]
@theswerd - see @advayDev1's comment on the original PR:
https://github.com/WorldHealthOrganization/app/pull/1206/files

Screen Shot 2020-12-26 at 9 39 07 PM

**Comment by theswerd** [comment]
I understand wanting to hide the app bundle, but I don't think it makes sense to hide the app directory, as it makes it invisible from within the root directory of the project.

**Comment by advayDev1** [comment]
The mistake was changing client/app -> to client/

client/flutter was the real code client/app was the symlink.

Just remove the client/ line.

**Comment by theswerd** [comment]
Sounds good

**Pull request merged**
