### PR TITLE
simple_connectivity v0.0.1 => connectivity v2.0.0

### LINKED ISSUE #1532: Connectivity no location permissions proper fix
Replace `simple_connectivity` with official `connectivity` plugin once it's able to work without requiring location permissions. This is dependant on the Flutter plugin team approving a fix.

Issue: https://github.com/flutter/flutter/issues/40418#issuecomment-694445064
Fix: https://github.com/flutter/plugins/pull/2771

- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).
- [x] Issue has descriptive title focused on the feature or problem from the user's perspective

### PR DESCRIPTION
**Pull request by brunobowden**
- Closes #1532
- Replace 3rd party simple_connectivity with Google connectivity package
- New version removes dependency on locations permission:
   - https://pub.dev/packages/connectivity/changelog#200
- compileSdkVersion 29 - matching targetSdk and Flutter packages

## Screenshots

<details>
<summary>Screenshots</summary>
Add any relevant before/after screenshots here
</details>

## How did you test the change?

Will test later with device turning on and off wifi access

- [ ] iOS Simulator
- [ ] iOS Device
- [ ] Android Simulator
- [ ] Android Device
- [ ] `curl` to a dev App Engine server
- [ ] other, please describe

## Checklist:

- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md) and verified that all contributions are properly licensed pursuant to the [LICENSE](https://github.com/WorldHealthOrganization/app/blob/master/LICENSE).

### CODE REVIEW

**Comment by brunobowden** [comment]
FYI @Mohit020888 - see if you can figure out a good way to test this

**Review by theswerd — DISMISSED** [review]
LGTM

**Comment by brunobowden** [comment]
@cyanglaz - thanks for the updating Connectivity to v2.0.0. You put a lot of care in to the deprecation message, v2.0.0 as breaking change and so on. Sorry to trouble you further but could I have you take a look at this CI issue I'm seeing after the upgrade:

The conflict was with PR: https://github.com/flutter/plugins/pull/3042 where `compileSdkVersion 29` was added in `connectivity v0.4.9+5`. I think plugin may be fine but it's causing some interaction with our CI. Our CI uses Java 12 - see [workflow](https://github.com/WorldHealthOrganization/app/blob/master/.github/workflows/client.yaml#L84-L86). After the update, it fails on a Java warning for `source value 7 is obsolete`. That same warning occured with `connectivity v0.4.9+3` but it didn't fail the build.

I didn't want to take up too much of your time but I'd appreciate some pointers for fixing this issue.

[CI Build Error](https://github.com/WorldHealthOrganization/app/pull/1669/checks?check_run_id=1307143216)
```
Running Gradle task 'assembleRelease'...                        
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
error: warnings found and -Werror specified
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':connectivity:compileReleaseJavaWithJavac'.
```

**Comment by cyanglaz** [comment]
I'm not too familiar with Android stuff. But it looks like you could switch to android 29 on ci?

**Comment by brunobowden** [comment]
@cyanglaz - I changed `compileSdkVersion` from 28 to 29 as part of the PR. Still looking in to this.

**Review by theswerd — APPROVED** [review]
LGTM

**Comment by brunobowden** [comment]
@yukuairoy - needs your approval too

**Comment by brunobowden** [comment]
@cyanglaz - figured out the problem was that the `connectivity` plugin recently started treating all warnings as errors.... so a warning about Java 7 target becoming obsolete now causes the build to fail. Temporary workaround is to downgrade to Java 11 environment (which doesn't treat Java 7 target as obsolete). Proper fix is Java 8 target for all Flutter plugins that have the `Werror` flag: https://github.com/flutter/plugins/pull/3216

https://github.com/flutter/plugins/pull/3216

**Review by yukuairoy — APPROVED** [review]

**Pull request merged**
