### PR TITLE
Removes Ionic React client

### PR DESCRIPTION
**Pull request by advayDev1**
BREAKING DEV CHANGE: We no longer use husky git hooks.  As long as you have no personal git hooks, run `pushd .git/hooks && ( ls | grep \.sample -v | xargs rm ) && popd` after you sync past this commit if you had built the ionic react client previously.

## Did you add any dependencies?

No, removed all deps from ionic react.

## How did you test the change?

Build

### CODE REVIEW

**Comment by advayDev1** [comment]
@hspinks depends on you disabling NPM-based snyk first to have green build

**Comment by hspinks** [comment]
@advayDev1 should be disabled

**Comment by advayDev1** [comment]
still enabled it appears @hspinks 
https://app.snyk.io/org/who-app/pr-checks/3dae8f25-3032-44c9-98f5-40704cd36602

**Comment by hspinks** [comment]
weird, @advayDev1 try it again now?

**Pull request merged**
